theme = "noctalia-overrides"

[editor.file-picker]
hidden = false
git-ignore = true

[keys.normal]

# Ctrl-y: open Yazi at the current file, then open the selected file in Helix.
C-y = [
  ':sh rm -f /tmp/helix-yazi-picker',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/helix-yazi-picker',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/helix-yazi-picker}',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]

# Ctrl-g: open LazyGit with the current file's history.
C-g = [
  ':insert-output lazygit -f "%{buffer_name}" -sm half </dev/tty >/dev/tty 2>&1',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]
