theme = "noctalia-overrides"

[editor.file-picker]
hidden = false
git-ignore = true

# Open Yazi as an interactive file-tree picker and load the selected file(s).
[keys.normal]
C-y = [
  ':sh rm -f /tmp/unique-ca1ea106',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-ca1ea106',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-ca1ea106}',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]
