#!/usr/bin/env bash

set -Eeuo pipefail

GHOSTTY_THEME_MENU="${GHOSTTY_THEME_MENU:-$HOME/.config/ghostty/ghostty-theme-menu.sh}"
NOCTALIA="${NOCTALIA:-noctalia}"
NIRI="${NIRI:-niri}"
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
ZEN_BROWSER_THEME_CONFIG="${ZEN_BROWSER_THEME_CONFIG:-$CONFIG_HOME/niri/zen-browser-theme.kdl}"

main_items=(
  "󰊠 Ghostty"
  "󰙨 Zen Browser"
)

fail() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

notify() {
  local title="$1"
  local message="$2"

  if command -v notify-send >/dev/null 2>&1; then
    notify-send "$title" "$message"
  else
    printf '%s: %s\n' "$title" "$message" >&2
  fi
}

choose_menu() {
  local prompt="$1"
  shift

  printf '%s\n' "$@" |
    "$NOCTALIA" dmenu -p "$prompt" || true
}

get_zen_browser_theme() {
  if [[ -r "$ZEN_BROWSER_THEME_CONFIG" ]] &&
    grep -Eq '^[[:space:]]*opacity[[:space:]]+0([.]70?|[.]7)[[:space:]]*$' "$ZEN_BROWSER_THEME_CONFIG"; then
    printf 'transparent\n'
  else
    printf 'opaque\n'
  fi
}

restore_theme_config() {
  local backup="$1"
  local had_original="$2"

  if [[ "$had_original" == true ]]; then
    mv -f -- "$backup" "$ZEN_BROWSER_THEME_CONFIG"
  else
    rm -f -- "$ZEN_BROWSER_THEME_CONFIG" "$backup"
  fi
}

set_zen_browser_theme() {
  local mode="$1"
  local config_dir temporary backup validation_output reload_output
  local had_original=false

  case "$mode" in
  opaque|transparent) ;;
  *)
    notify "Zen Browser" "Unknown theme mode: $mode"
    return 1
    ;;
  esac

  config_dir="$(dirname -- "$ZEN_BROWSER_THEME_CONFIG")"
  [[ ! -L "$config_dir" ]] || {
    notify "Zen Browser" "Niri config directory must be a real directory"
    return 1
  }
  [[ ! -L "$ZEN_BROWSER_THEME_CONFIG" ]] || {
    notify "Zen Browser" "Generated theme config must be a machine-local file"
    return 1
  }

  install -d -m 700 "$config_dir"
  temporary="$(mktemp --tmpdir="$config_dir" '.zen-browser-theme.XXXXXX.kdl')"
  backup="$(mktemp --tmpdir="$config_dir" '.zen-browser-theme.backup.XXXXXX.kdl')"

  if [[ -e "$ZEN_BROWSER_THEME_CONFIG" ]]; then
    cp -- "$ZEN_BROWSER_THEME_CONFIG" "$backup"
    had_original=true
  fi

  if [[ "$mode" == "transparent" ]]; then
    cat >"$temporary" <<'EOF'
// Generated by Niri's theme launcher. Do not track this machine-local file.
window-rule {
    match app-id=r#"^zen$"#
    // Do not let Niri's focus-ring backing rectangle show through Zen.
    draw-border-with-background false
    opacity 0.70
}
EOF
  else
    cat >"$temporary" <<'EOF'
// Generated by Niri's theme launcher: Zen uses its normal opaque surface.
EOF
  fi

  chmod 600 "$temporary"
  mv -f -- "$temporary" "$ZEN_BROWSER_THEME_CONFIG"

  if ! validation_output="$("$NIRI" validate 2>&1)"; then
    restore_theme_config "$backup" "$had_original"
    notify "Zen Browser" "Theme was not applied because Niri validation failed: $validation_output"
    return 1
  fi

  if ! reload_output="$("$NIRI" msg action load-config-file 2>&1)"; then
    restore_theme_config "$backup" "$had_original"
    "$NIRI" msg action load-config-file >/dev/null 2>&1 || true
    notify "Zen Browser" "Theme was rolled back because Niri reload failed: $reload_output"
    return 1
  fi

  rm -f -- "$backup"
}

choose_zen_browser() {
  local mode choice
  local opaque_label="󰞏 Opaque + No Blur"
  local transparent_label="󰹞 Transparent + Blur"

  mode="$(get_zen_browser_theme)"
  if [[ "$mode" == "opaque" ]]; then
    opaque_label="● $opaque_label"
  else
    transparent_label="● $transparent_label"
  fi

  choice="$(choose_menu "Zen Browser > " "$opaque_label" "$transparent_label")"
  [[ -z "$choice" ]] && return 0

  case "$choice" in
  "$opaque_label")
    set_zen_browser_theme opaque
    notify "Zen Browser" "Opaque, blur hidden by the window surface"
    ;;

  "$transparent_label")
    set_zen_browser_theme transparent
    notify "Zen Browser" "Opacity 0.70, Niri blur visible"
    ;;
  esac
}

main() {
  local choice

  if (($# != 0)); then
    printf 'Usage: %s\n' "${0##*/}" >&2
    return 2
  fi

  command -v "$NOCTALIA" >/dev/null 2>&1 || fail "Noctalia is required: $NOCTALIA"
  command -v "$NIRI" >/dev/null 2>&1 || fail "Niri is required: $NIRI"
  [[ -x "$GHOSTTY_THEME_MENU" ]] || fail "Ghostty theme menu is not executable: $GHOSTTY_THEME_MENU"

  choice="$(choose_menu "Theme Target > " "${main_items[@]}")"
  [[ -z "$choice" ]] && return 0

  case "$choice" in
  "󰊠 Ghostty") "$GHOSTTY_THEME_MENU" ;;
  "󰙨 Zen Browser") choose_zen_browser ;;
  esac
}

main "$@"
